namespace: user-mgmt-staging
replicaCount:
  backend: 1
  frontend: 1
  moduleService: 1
ingress:
  host: staging.localhost
hpa:
  backend:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
