namespace: user-mgmt

images:
  backend: sidardenli/user-mgmt-service:c3a42f9
  frontend: sidardenli/auth_portal:latest
  postgres: postgres:16-alpine

replicaCount:
  backend: 1
  frontend: 1

secrets:
  springDatasourcePassword: "mysecretpassword"
  postgresPassword: "mysecretpassword"
  jwtSecret: "wIDAQABAkAzGlFARFau7K0b9FcEwIDAQABAkAzGlFARFau7K0b9FcEwIDAQABAkAzGlFARFau7K0b9FcE"

config:
  springDatasourceUrl: "jdbc:postgresql://postgres:5432/postgres"