apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - job-user-mgmt.yaml
  - job-module-assignment.yaml

# Die Testskripte werden automatisch in eine ConfigMap gepackt
configMapGenerator:
  - name: k6-scripts
    namespace: loadtest
    files:
      - scripts/user-mgmt-load-test.js
      - scripts/module-assignment-load-test.js

generatorOptions:
  disableNameSuffixHash: true
